name: Upload Script To S3

on:
  push:
    paths:
      - 'TF/upload.sh'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload File To S3
        run: |
          aws s3 cp TF/upload.sh s3://${{ secrets.S3_BUCKET }}/scripts/upload.sh